# Generated by Django 4.2.1 on 2023-05-21 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KGTravelGuide', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='attachments/', verbose_name='Attachment')),
                ('file_type', models.CharField(choices=[('Photo', 'PHOTO'), ('VIDEO', 'VIDEO')], max_length=10, verbose_name='File type')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KGTravelGuide.place', verbose_name='Place')),
            ],
            options={
                'verbose_name': 'Attachment',
                'verbose_name_plural': 'Attachments',
            },
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.AlterField(
            model_name='place',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='KGTravelGuide.attachment'),
        ),
    ]
