# Generated by Django 4.2.1 on 2023-05-21 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KGTravelGuide', '0003_city_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='KGTravelGuide.city'),
        ),
        migrations.AlterField(
            model_name='place',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='KGTravelGuide.region'),
        ),
    ]
