# Generated by Django 4.2.1 on 2023-05-21 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KGTravelGuide', '0004_alter_place_city_alter_place_region'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={},
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='publication',
        ),
    ]
