# Generated by Django 4.2.1 on 2023-05-27 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KGTravelGuide', '0006_alter_attachment_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.ImageField(upload_to='KGTravelGuide/attachments/', verbose_name='Attachment'),
        ),
    ]
