# Generated by Django 4.2.1 on 2023-06-02 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KGTravelGuide', '0008_place_latitude_place_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='photo', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WorkHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.TimeField()),
            ],
        ),
        migrations.AddField(
            model_name='attachment',
            name='name',
            field=models.CharField(default='photo', max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='KGTravelGuide.city')),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='KGTravelGuide.attachment')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='KGTravelGuide.region')),
                ('tags', models.ManyToManyField(to='KGTravelGuide.tag')),
                ('work_days', models.ManyToManyField(to='KGTravelGuide.workday')),
                ('work_hours', models.ManyToManyField(to='KGTravelGuide.workhour')),
            ],
        ),
    ]
