# Generated by Django 4.2.1 on 2023-06-02 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KGTravelGuide', '0011_alter_hotel_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='work_hours',
        ),
        migrations.AddField(
            model_name='hotel',
            name='closing_hour',
            field=models.TimeField(default='23:59:59'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='opening_hour',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.DeleteModel(
            name='WorkHour',
        ),
    ]
