# Generated by Django 4.2.1 on 2023-06-02 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KGTravelGuide', '0012_remove_hotel_work_hours_hotel_closing_hour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='closing_hour',
            field=models.TimeField(default='23:59'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='opening_hour',
            field=models.TimeField(default='00:00'),
        ),
        migrations.CreateModel(
            name='PlaceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField()),
                ('comment', models.TextField()),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='KGTravelGuide.place')),
            ],
        ),
        migrations.CreateModel(
            name='HotelReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField()),
                ('comment', models.TextField()),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='KGTravelGuide.hotel')),
            ],
        ),
    ]
