# Generated by Django 4.2.1 on 2023-06-02 09:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KGTravelGuide', '0013_alter_hotel_closing_hour_alter_hotel_opening_hour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelreview',
            name='rating',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='placereview',
            name='rating',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
